server:
  port: 8082

#logging:
#  level:
#    root: debug

spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test;MODE=MYSQL
    driver-class-name: org.h2.Driver

jwt:
  secret: hellomyounginhellomyounginhellomyounginhellomyounginhellomyounginhellomyounginhellomyounginhellomyoungin
  duration: 30